### ISSUE TITLE
when will lightdeq support Cuda 11.0?

### ISSUE THREAD

**Issue by YINGPENGZH** [bytedance/lightseq#251] opened 2021-12-30 07:27 UTC
Could you please make the lightseq support the cuda 11? cuz i have a large amount of data to generate with gpt2.

**Comment by Taka152** [comment] 2021-12-31 04:19
LightSeq works fine with cuda 11.

**Comment by YINGPENGZH** [comment] 2021-12-31 07:22
> LightSeq works fine with cuda 11.

Sorry, I ignore something details. Can lightseq inference run driver greater than 450 now?

**Comment by Taka152** [comment] 2022-01-04 09:38
I tested on 470, it works fine.

**Comment by Taka152** [comment] 2022-01-06 15:20
That may caused by A100. Lightseq should be recompiled to support A100. 80 need to be added here.
https://github.com/bytedance/lightseq/blob/fbe5399c3cda0dc5bb43fc12797195840022d9c5/CMakeLists.txt#L4

**Comment by YINGPENGZH** [comment] 2022-01-17 08:33
> That may caused by A100. Lightseq should be recompiled to support A100. 80 need to be added here.
> 
> https://github.com/bytedance/lightseq/blob/fbe5399c3cda0dc5bb43fc12797195840022d9c5/CMakeLists.txt#L4

Hello, could you offer a tutorial to recompile lightseq? I download the 3rdparty cub and ptbind11 in image1, but I failed to build them. Thank you.
And the error in image 2.
image1:  
![image](https://user-images.githubusercontent.com/21099446/149734208-401e6055-195f-4639-9665-3bd61683260d.png)
image2:
![image](https://user-images.githubusercontent.com/21099446/149734652-39b6ecc5-f22c-42ed-9e8f-80407a5e71af.png)

**Comment by kaierlong** [comment] 2022-01-17 09:55
@Taka152 
Which branch did you test on nvidia driver 470?
Is the v2.2.0 support that?

**Comment by Taka152** [comment] 2022-01-17 09:57
> > That may caused by A100. Lightseq should be recompiled to support A100. 80 need to be added here.
> > https://github.com/bytedance/lightseq/blob/fbe5399c3cda0dc5bb43fc12797195840022d9c5/CMakeLists.txt#L4
> 
> Hello, could you offer me a tutorial or environment requirements to recompile lightseq ? I download the 3rdparty cub and ptbind11 in image1, but I failed to build them. Thank you. And the error in image 2. image1: ![image](https://user-images.githubusercontent.com/21099446/149734208-401e6055-195f-4639-9665-3bd61683260d.png) image2: ![image](https://user-images.githubusercontent.com/21099446/149734652-39b6ecc5-f22c-42ed-9e8f-80407a5e71af.png)

I guess you are building using cuda 10, native build for A100 should use cuda11.

**Comment by Taka152** [comment] 2022-01-17 09:58
@kaierlong latest pypi version with driver 470.57.02, cuda 11.4 and 1080Ti

**Comment by kaierlong** [comment] 2022-01-17 10:04
@Taka152 
I need to build so file which used for NV Triton Inference Server.
And the doc file -- docs/inference/build.md says it must build below cuda 11.0.
So I'm trying to kown whether the so file could be supported on driver 470+.
Or any case for than driver version.

**Comment by YINGPENGZH** [comment] 2022-01-26 04:00
> > > That may caused by A100. Lightseq should be recompiled to support A100. 80 need to be added here.
> > > https://github.com/bytedance/lightseq/blob/fbe5399c3cda0dc5bb43fc12797195840022d9c5/CMakeLists.txt#L4
> > 
> > 
> > Hello, could you offer me a tutorial or environment requirements to recompile lightseq ? I download the 3rdparty cub and ptbind11 in image1, but I failed to build them. Thank you. And the error in image 2. image1: ![image](https://user-images.githubusercontent.com/21099446/149734208-401e6055-195f-4639-9665-3bd61683260d.png) image2: ![image](https://user-images.githubusercontent.com/21099446/149734652-39b6ecc5-f22c-42ed-9e8f-80407a5e71af.png)
> 
> @YINGPENGZH Try cuda 11 to build should solve this error. Tutorial for cuda 10 is [here](https://github.com/bytedance/lightseq/blob/2e1cf1aa184a011cb71c17acbd4139144188ce7d/docs/inference/build.md)

Could you give me a specific env list to build with cuda11 and A100 like gcc, hdf5's version?  I encounter some errors when building lightseq.
The following is hdf5's error
![image](https://user-images.githubusercontent.com/21099446/151101821-64baa737-3595-4584-b4e0-aaa47285577a.png)

**Comment by Taka152** [comment] 2022-01-26 04:45
The version is fixed in the build tutorial. You only need to upgrade your cuda toolkit.
________________________________
发件人: LiaoFei ***@***.***>
发送时间: Wednesday, January 26, 2022 12:00:25 PM
收件人: bytedance/lightseq ***@***.***>
抄送: Ying Xiong ***@***.***>; Mention ***@***.***>
主题: Re: [bytedance/lightseq] when will lightdeq support Cuda 11.0? (Issue #251)


That may caused by A100. Lightseq should be recompiled to support A100. 80 need to be added here.
https://github.com/bytedance/lightseq/blob/fbe5399c3cda0dc5bb43fc12797195840022d9c5/CMakeLists.txt#L4

Hello, could you offer me a tutorial or environment requirements to recompile lightseq ? I download the 3rdparty cub and ptbind11 in image1, but I failed to build them. Thank you. And the error in image 2. image1: [image] <https://user-images.githubusercontent.com/21099446/149734208-401e6055-195f-4639-9665-3bd61683260d.png>  image2: [image] <https://user-images.githubusercontent.com/21099446/149734652-39b6ecc5-f22c-42ed-9e8f-80407a5e71af.png>

@YINGPENGZH<https://github.com/YINGPENGZH> Try cuda 11 to build should solve this error. Tutorial for cuda 10 is here<https://github.com/bytedance/lightseq/blob/2e1cf1aa184a011cb71c17acbd4139144188ce7d/docs/inference/build.md>

Could you give me a specific env list to build with cuda11 and A100 like gcc, hdf5's version? I encounter some errors when building lightseq.
The following is hdf5's error
[image]<https://user-images.githubusercontent.com/21099446/151101821-64baa737-3595-4584-b4e0-aaa47285577a.png>

―

**Closed** 2022-06-20 01:33 UTC
